import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FAQ Generator from Website",
  description: "Generated by create next app",
};

/**
 * Root Layout Component
 *
 * The main application layout wrapper that provides global context and styling.
 * Wraps the entire Next.js application with essential providers.
 *
 * Providers:
 * - ThemeProvider: Manages dark/light theme state and persistence
 * - AuthProvider: Initializes authentication state and user session
 * - Toaster: Global toast notification system (Sonner)
 *
 * Features:
 * - Inter font from Google Fonts
 * - Global CSS styling
 * - Antialiased text rendering
 * - Metadata for SEO
 *
 * Provider Order (important for context dependencies):
 * 1. ThemeProvider (outermost)
 * 2. AuthProvider (needs theme context)
 * 3. Children (app pages)
 * 4. Toaster (toast notifications, separate from provider tree)
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ThemeProvider>
        <Toaster/>
      </body>
    </html>
  );
}
